### ISSUE TITLE
Add repository prefix

### ISSUE THREAD

**Issue by moltar** [sapphi-red/vitest-github-actions-reporter#6]
Not sure if this is something new or not, but in our runs, the prefix is not what you have hard-coded:

https://github.com/sapphi-red/vitest-github-actions-reporter/blob/e067dbb7fcbe2754d40ad76c33ef5ace16f641ec/src/stacktrace/stringify.ts#L4-L7

It is:

```
/home/runner/actions-runner/_work/
```

![screenshot-20231129T212908-GKOYSDjC@2x](https://github.com/sapphi-red/vitest-github-actions-reporter/assets/491247/54d26a61-6e43-4024-afcc-f7a926df680c)

**Comment by moltar** [comment]
Also, maybe using `GITHUB_WORKSPACE` env var is better?

https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

![screenshot-20231129T213257-H1YQWduQ@2x](https://github.com/sapphi-red/vitest-github-actions-reporter/assets/491247/66745831-620b-4fb9-85ce-4a91768e9cf7)

**Comment by sapphi-red** [comment]
@moltar I released v0.11.1 that uses `GITHUB_WORKSPACE` env var 👍

**Comment by moltar** [comment]
Amazing, thank you 😀
